# Generated by Django 3.2.9 on 2021-11-17 08:35

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.TextField(default='')),
                ('secret_key', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'connected_exchange',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=10)),
                ('exchange_image', models.FileField(default='', upload_to=exchange.models.exchange_directory_path)),
                ('location', models.CharField(choices=[('domestic', 'Domestic'), ('aboard', 'Aboard')], max_length=8)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=40)),
                ('side', models.CharField(default='', max_length=3)),
                ('ord_type', models.CharField(default='', max_length=7)),
                ('price', models.FloatField()),
                ('state', models.CharField(default='', max_length=5)),
                ('market', models.CharField(default='', max_length=20)),
                ('volume', models.FloatField()),
                ('remaining_volume', models.FloatField()),
                ('reserved_fee', models.FloatField()),
                ('remaining_fee', models.FloatField()),
                ('paid_fee', models.FloatField()),
                ('locked', models.FloatField()),
                ('executed_volume', models.FloatField()),
                ('trades_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('connected_exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.connectedexchange')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='connectedexchange',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.exchange'),
        ),
    ]
