# Generated by Django 3.2.9 on 2021-11-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_connectedexchange_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='location',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('aboard', 'Aboard')], max_length=8),
        ),
    ]
