# Generated by Django 3.2.9 on 2021-11-17 11:21

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_connectedexchange_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to=exchange.models.exchange_description_directory_path)),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.exchange')),
            ],
        ),
    ]
