# Generated by Django 2.1 on 2021-11-15 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0002_auto_20211114_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=40)),
                ('side', models.CharField(default='', max_length=3)),
                ('order_type', models.CharField(default='', max_length=7)),
                ('price', models.FloatField()),
                ('state', models.CharField(default='', max_length=5)),
                ('market', models.CharField(default='', max_length=20)),
                ('volume', models.FloatField()),
                ('remaining_volume', models.FloatField()),
                ('reserved_fee', models.FloatField()),
                ('remaining_fee', models.FloatField()),
                ('paid_fee', models.FloatField()),
                ('locked', models.FloatField()),
                ('executed_volume', models.FloatField()),
                ('trade_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.Exchange')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
