# Generated by Django 3.2.9 on 2021-11-18 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_exchangedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangedescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
