# Generated by Django 3.2.9 on 2021-11-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20211116_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_image',
            field=models.FileField(upload_to=''),
        ),
    ]
