# Generated by Django 3.2.9 on 2021-11-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_exchange_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='exchange_type',
            new_name='exchange_name',
        ),
    ]
