# Generated by Django 3.2.9 on 2021-11-16 05:37

from django.db import migrations, models
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_exchange_exchange_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_image',
            field=models.FileField(default='', upload_to=exchange.models.exchange_directory_path),
        ),
    ]
