# Generated by Django 3.2.9 on 2021-11-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20211118_1131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exchangedescription',
            table='exchange_description',
        ),
    ]
