# Generated by Django 2.1 on 2021-11-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20211115_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='api_key',
            new_name='access_key',
        ),
        migrations.AlterField(
            model_name='upbit',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.Exchange'),
        ),
    ]
