# Generated by Django 3.2.9 on 2021-11-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_exchangedescription_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='has_qr',
            field=models.BooleanField(default=False),
        ),
    ]
