# Generated by Django 3.2.9 on 2021-11-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_exchange_exchange_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_image',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
