# Generated by Django 3.2.9 on 2021-11-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_exchange_has_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exchange_color',
            field=models.CharField(default='0xFF1045FF', max_length=10),
        ),
    ]
