# Generated by Django 2.1 on 2021-11-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20211115_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upbit',
            old_name='order_type',
            new_name='ord_type',
        ),
        migrations.RenameField(
            model_name='upbit',
            old_name='trade_count',
            new_name='trades_count',
        ),
        migrations.AlterField(
            model_name='upbit',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.Exchange'),
        ),
    ]
