# Generated by Django 2.1 on 2021-11-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20211115_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upbit',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.Exchange'),
        ),
    ]
