# Generated by Django 3.2.9 on 2021-11-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_exchange_exchange_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
