# Generated by Django 3.2.9 on 2021-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_asset_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedexchange',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
