# Generated by Django 2.1 on 2021-11-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20211115_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upbit',
            name='exchange',
        ),
    ]
