# Generated by Django 3.2.9 on 2021-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active2',
            field=models.BooleanField(default=True),
        ),
    ]
