# Generated by Django 3.2.9 on 2021-12-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active2',
            new_name='now_active',
        ),
    ]
